[build.environment]
  NPM_FLAGS = "--prefix=/dev/null"
  NODE_VERSION = "14"

[build]
  publish = "dist/ssg"
  command = "yarn install && quasar ssg generate"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

